//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Order
{
    public Order()
    {
        this.Recipients = new HashSet<Recipient>();
    }

    public int Id { get; set; }
    public Nullable<int> SenderId { get; set; }

    public virtual ICollection<Recipient> Recipients { get; set; }
    public virtual Sender Sender { get; set; }
}

public partial class Package
{
    public Package()
    {
        this.PackageDetails = new HashSet<PackageDetail>();
    }

    public int Id { get; set; }
    public decimal Length { get; set; }
    public decimal Width { get; set; }
    public decimal Height { get; set; }
    public decimal Weight { get; set; }
    public string WaybillNumber { get; set; }
    public int RecipientID { get; set; }

    public virtual ICollection<PackageDetail> PackageDetails { get; set; }
    public virtual Recipient Recipient { get; set; }
}

public partial class PackageDetail
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public int PackageID { get; set; }

    public virtual Package Package { get; set; }
}

public partial class PriceItem
{
    public int Id { get; set; }
    public decimal Weight { get; set; }
    public decimal Price { get; set; }
    public int PriceListID { get; set; }

    public virtual PriceList PriceList { get; set; }
}

public partial class PriceList
{
    public PriceList()
    {
        this.PriceItems = new HashSet<PriceItem>();
        this.Services = new HashSet<Service>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<PriceItem> PriceItems { get; set; }
    public virtual ICollection<Service> Services { get; set; }
}

public partial class Recipient
{
    public Recipient()
    {
        this.Packages = new HashSet<Package>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string City { get; set; }
    public string Address { get; set; }
    public string ZipCode { get; set; }
    public string PhoneNumber { get; set; }
    public Nullable<int> OrderId { get; set; }

    public virtual ICollection<Package> Packages { get; set; }
    public virtual Order Order { get; set; }
}

public partial class Sender
{
    public Sender()
    {
        this.Orders = new HashSet<Order>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string City { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string Address3 { get; set; }
    public string Phone { get; set; }
    public string ZipCode { get; set; }

    public virtual ICollection<Order> Orders { get; set; }
}

public partial class Service
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string PictureLink { get; set; }
    public string Discribe { get; set; }
    public string DiscribePictureLink { get; set; }
    public bool PickUpService { get; set; }
    public Nullable<int> PriceListID { get; set; }
    public string PickUpCompany { get; set; }

    public virtual PriceList PriceList { get; set; }
}
